# Compiler used to build the project
CC = gcc

# Tool used to generate C code from the Flex lexer
FLEX = flex

# Compilation flags:
# -Wall   enables common warnings
# -Wextra enables extra warnings
# -g      adds debug information
# -Isrc   allows the compiler to find header files inside the src folder
CFLAGS = -Wall -Wextra -g -Isrc

# Name of the executable that will be generated
TARGET = poLite

# Project folders
SRC_DIR = src
TEST_DIR = test
BUILD_DIR = build

# Lexer source file
LEXER = $(SRC_DIR)/lexer.l

# C file generated by Flex from lexer.l
LEXER_C = $(BUILD_DIR)/lex.yy.c

# Symbol table files
SYMBOL_TABLE_C = $(SRC_DIR)/symbol_table.c
SYMBOL_TABLE_H = $(SRC_DIR)/symbol_table.h

# Symbol table test file
SYMBOL_TABLE_TEST = $(TEST_DIR)/test_symbol_table.c
SYMBOL_TABLE_TEST_TARGET = test_symbol_table

# Default target.
# When you run just `make`, this target is executed.
all: $(TARGET)

# Current temporary build:
# for now, poLite is generated from the standalone lexer.
#
# This compiles:
# - src/lexer.l      -> Flex lexer source
# - build/lex.yy.c   -> generated C file from Flex
#
# Important:
# src/lexer.l currently contains its own main function.
# Therefore, src/main.c is not used yet.
$(TARGET): $(LEXER_C)
	$(CC) $(CFLAGS) $(LEXER_C) -o $(TARGET)

# Generates the C lexer file from src/lexer.l.
#
# The -o option tells Flex where to write the generated file.
$(LEXER_C): $(LEXER)
	mkdir -p $(BUILD_DIR)
	$(FLEX) -o $(LEXER_C) $(LEXER)

# Runs the lexer in interactive mode.
#
# Run with:
# make run
run: $(TARGET)
	./$(TARGET)

# Runs the lexer on test/test_gentle.plt.
#
# Run with:
# make run-gentle
run-gentle: $(TARGET)
	./$(TARGET) $(TEST_DIR)/test_gentle.plt

# Runs the lexer on test/test_errors.plt.
#
# Run with:
# make run-errors
run-errors: $(TARGET)
	./$(TARGET) $(TEST_DIR)/test_errors.plt

# Builds the symbol table test executable.
#
# Run with:
# make test-symbol-table
test-symbol-table: $(SYMBOL_TABLE_TEST) $(SYMBOL_TABLE_C) $(SYMBOL_TABLE_H)
	$(CC) $(CFLAGS) $(SYMBOL_TABLE_TEST) $(SYMBOL_TABLE_C) -o $(SYMBOL_TABLE_TEST_TARGET)

# Runs the symbol table test.
#
# Run with:
# make run-symbol-table
run-symbol-table: test-symbol-table
	./$(SYMBOL_TABLE_TEST_TARGET)

# Removes generated files and executables.
#
# Run with:
# make clean
clean:
	rm -rf poLite.dSYM
	rm -rf $(BUILD_DIR)
	rm -f $(TARGET)
	rm -f $(SYMBOL_TABLE_TEST_TARGET)